//
//  RoutableRegistry.swift
//  Ios-MVVM
//
//  🤖 AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
//  This file is automatically generated by Scripts/generate_routable_registry.sh
//  To add a new route: implement Routable protocol in your ViewModel
//

import Foundation

@MainActor
class RoutableRegistry {
    /// All view models that can be routed to
    /// 🤖 This array is automatically generated from ViewModels conforming to Routable
    static let all: [any Routable.Type] = [
        FavoritesViewModel.self,
        HomeViewModel.self,
        OrdersViewModel.self,
        ProductDetailViewModel.self,
        ProductListViewModel.self,
        ReviewsViewModel.self,
    ]

    /// Registers all routable types with the coordinator
    /// - Parameter coordinator: The coordinator to register routes with
    static func registerAll(with coordinator: AppCoordinator) {
        all.forEach { routableType in
            coordinator.register(identifier: routableType.routeIdentifier) { route in
                routableType.createView(from: route, coordinator: coordinator)
            }
        }
    }
}
