#!/bin/bash

# Generate both Route.swift and RoutableTypes.swift by scanning ViewModels
# This script automatically discovers all ViewModels that conform to Routable

set -e

# Configuration
PROJECT_DIR="${SRCROOT}"
ROUTE_OUTPUT="${PROJECT_DIR}/Ios-MVVM/Presentation/Coordinator/Route.swift"
TYPES_OUTPUT="${PROJECT_DIR}/Ios-MVVM/Presentation/Coordinator/RoutableTypes.swift"
SEARCH_DIR="${PROJECT_DIR}/Ios-MVVM"

echo "🔍 Scanning for Routable types in: ${SEARCH_DIR}"

# Find all ViewModel files that conform to Routable
ROUTABLE_FILES=$(/usr/bin/find "${SEARCH_DIR}" -name "*ViewModel.swift" -type f -exec /usr/bin/grep -l "extension.*:.*Routable" {} \;)

# Extract type names and paths
declare -a TYPE_NAMES
declare -a TYPE_PATHS
declare -a TYPE_IDS

while IFS= read -r file; do
    if [ -n "$file" ]; then
        # Extract type name
        TYPE_NAME=$(/usr/bin/grep "extension.*:.*Routable" "$file" | /usr/bin/sed -E 's/.*extension[[:space:]]+([A-Za-z0-9_]+)[[:space:]]*:[[:space:]]*Routable.*/\1/')

        # Extract path from routeConfig
        PATH_LINE=$(/usr/bin/grep 'path:' "$file" | /usr/bin/head -1)
        if [[ $PATH_LINE =~ \"([^\"]+)\" ]]; then
            PATH="${BASH_REMATCH[1]}"
        else
            PATH=""
        fi

        # Generate route identifier from ViewModel name
        # HomeViewModel -> home, ProductDetailViewModel -> productDetail
        BASE_NAME=$(echo "$TYPE_NAME" | /usr/bin/sed 's/ViewModel$//')
        FIRST_CHAR=$(echo "$BASE_NAME" | /usr/bin/cut -c1 | /usr/bin/tr '[:upper:]' '[:lower:]')
        REST=$(echo "$BASE_NAME" | /usr/bin/cut -c2-)
        ROUTE_ID="${FIRST_CHAR}${REST}"

        if [ -n "$TYPE_NAME" ] && [ -n "$PATH" ]; then
            TYPE_NAMES+=("$TYPE_NAME")
            TYPE_PATHS+=("$PATH")
            TYPE_IDS+=("$ROUTE_ID")
        fi
    fi
done <<< "$ROUTABLE_FILES"

TYPE_COUNT=${#TYPE_NAMES[@]}
echo "✅ Found ${TYPE_COUNT} Routable types"

# Generate Route.swift
/bin/cat > "${ROUTE_OUTPUT}" << 'EOF'
//
//  Route.swift
//  Ios-MVVM
//
//  🤖 AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
//  Generated by Scripts/generate_routable_files.sh
//  Routes are derived from ViewModel paths
//

import Foundation

enum Route: Hashable {
EOF

# Add route cases
for i in "${!TYPE_NAMES[@]}"; do
    TYPE="${TYPE_NAMES[$i]}"
    PATH="${TYPE_PATHS[$i]}"
    ROUTE_ID="${TYPE_IDS[$i]}"

    # Check if path has parameters (contains :)
    if [[ $PATH == *":"* ]]; then
        # Extract model type from ViewModel name (e.g., ProductDetailViewModel -> Product)
        MODEL=$(echo "$TYPE" | /usr/bin/sed 's/DetailViewModel//' | /usr/bin/sed 's/ViewModel//')
        /bin/echo "    case ${ROUTE_ID}(${MODEL})" >> "${ROUTE_OUTPUT}"
    else
        /bin/echo "    case ${ROUTE_ID}" >> "${ROUTE_OUTPUT}"
    fi
done

# Add identifier property
/bin/cat >> "${ROUTE_OUTPUT}" << 'EOF'

    var identifier: String {
        Mirror(reflecting: self).children.first?.label ?? String(describing: self)
    }
}
EOF

echo "✅ Generated Route.swift with ${TYPE_COUNT} routes"

# Generate RoutableTypes.swift
/bin/cat > "${TYPES_OUTPUT}" << 'EOF'
//
//  RoutableTypes.swift
//  Ios-MVVM
//
//  🤖 AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
//  Generated by Scripts/generate_routable_files.sh
//  Generated at compile time - should be in .gitignore
//

import Foundation

/// Auto-generated list of all routable view model types
@MainActor
let routableTypes: [any Routable.Type] = [
EOF

# Add each type to the array
for TYPE in "${TYPE_NAMES[@]}"; do
    /bin/echo "    ${TYPE}.self," >> "${TYPES_OUTPUT}"
done

/bin/cat >> "${TYPES_OUTPUT}" << 'EOF'
]
EOF

echo "✅ Generated RoutableTypes.swift with ${TYPE_COUNT} types"
echo "📝 Registered types:"
for i in "${!TYPE_NAMES[@]}"; do
    /bin/echo "   - ${TYPE_NAMES[$i]} (${TYPE_PATHS[$i]})"
done
