#!/bin/bash

# Generate RoutableTypes.swift by scanning for Routable conformances
# This script automatically discovers all ViewModels that conform to Routable

set -e

# Configuration
PROJECT_DIR="${SRCROOT}"
OUTPUT_FILE="${PROJECT_DIR}/Ios-MVVM/Presentation/Coordinator/RoutableTypes.swift"
SEARCH_DIR="${PROJECT_DIR}/Ios-MVVM"

echo "🔍 Scanning for Routable types in: ${SEARCH_DIR}"

# Find all Swift files and extract types that conform to Routable
ROUTABLE_TYPES=$(find "${SEARCH_DIR}" -name "*.swift" -type f -exec grep -l "extension.*:.*Routable" {} \; | \
    xargs grep "extension.*:.*Routable" | \
    sed -E 's/.*extension[[:space:]]+([A-Za-z0-9_]+)[[:space:]]*:[[:space:]]*Routable.*/\1/' | \
    sort -u)

# Count found types
TYPE_COUNT=$(echo "${ROUTABLE_TYPES}" | grep -c . || echo "0")
echo "✅ Found ${TYPE_COUNT} Routable types"

# Generate the Swift file content
cat > "${OUTPUT_FILE}" << 'EOF'
//
//  RoutableTypes.swift
//  Ios-MVVM
//
//  🤖 AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
//  This file is automatically generated by Scripts/generate_routable_registry.sh
//  Generated at compile time - should be in .gitignore
//

import Foundation

/// Auto-generated list of all routable view model types
/// Generated by scanning for ViewModels conforming to Routable protocol
@MainActor
let routableTypes: [any Routable.Type] = [
EOF

# Add each type to the array
while IFS= read -r type; do
    if [ -n "$type" ]; then
        echo "    ${type}.self," >> "${OUTPUT_FILE}"
    fi
done <<< "${ROUTABLE_TYPES}"

# Close the array
cat >> "${OUTPUT_FILE}" << 'EOF'
]
EOF

echo "✅ Generated RoutableTypes.swift with ${TYPE_COUNT} types"
echo "📝 Registered types:"
echo "${ROUTABLE_TYPES}" | sed 's/^/   - /'
