#!/bin/bash

# Generate RoutableRegistry.swift by scanning for Routable conformances
# This script automatically discovers all ViewModels that conform to Routable

set -e

# Configuration
PROJECT_DIR="${SRCROOT}"
OUTPUT_FILE="${PROJECT_DIR}/Ios-MVVM/Presentation/Coordinator/RoutableRegistry.swift"
SEARCH_DIR="${PROJECT_DIR}/Ios-MVVM"

echo "🔍 Scanning for Routable types in: ${SEARCH_DIR}"

# Find all Swift files and extract types that conform to Routable
ROUTABLE_TYPES=$(find "${SEARCH_DIR}" -name "*.swift" -type f -exec grep -l "extension.*:.*Routable" {} \; | \
    xargs grep "extension.*:.*Routable" | \
    sed -E 's/.*extension[[:space:]]+([A-Za-z0-9_]+)[[:space:]]*:[[:space:]]*Routable.*/\1/' | \
    sort -u)

# Count found types
TYPE_COUNT=$(echo "${ROUTABLE_TYPES}" | grep -c . || echo "0")
echo "✅ Found ${TYPE_COUNT} Routable types"

# Generate the Swift file content
cat > "${OUTPUT_FILE}" << 'EOF'
//
//  RoutableRegistry.swift
//  Ios-MVVM
//
//  🤖 AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
//  This file is automatically generated by Scripts/generate_routable_registry.sh
//  To add a new route: implement Routable protocol in your ViewModel
//

import Foundation

@MainActor
class RoutableRegistry {
    /// All view models that can be routed to
    /// 🤖 This array is automatically generated from ViewModels conforming to Routable
    static let all: [any Routable.Type] = [
EOF

# Add each type to the array
while IFS= read -r type; do
    if [ -n "$type" ]; then
        echo "        ${type}.self," >> "${OUTPUT_FILE}"
    fi
done <<< "${ROUTABLE_TYPES}"

# Close the array and add the registerAll method
cat >> "${OUTPUT_FILE}" << 'EOF'
    ]

    /// Registers all routable types with the coordinator
    /// - Parameter coordinator: The coordinator to register routes with
    static func registerAll(with coordinator: AppCoordinator) {
        all.forEach { routableType in
            coordinator.register(identifier: routableType.routeIdentifier) { route in
                routableType.createView(from: route, coordinator: coordinator)
            }
        }
    }
}
EOF

echo "✅ Generated ${OUTPUT_FILE}"
echo "📝 Registered types:"
echo "${ROUTABLE_TYPES}" | sed 's/^/   - /'
